[theme]
base = "light"
primaryColor = "#0B72E7"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
